---
ID: "f9697d76-b9bc-4258-8fc9-1c33cc287be6"
Parent: "98a3d034-92e4-4ecb-9632-119cabd08e15"
Template: "98a3d034-92e4-4ecb-9632-119cabd08e15"
Path: /sitecore/templates/Project/Common/Content Types/Site Root/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180226T123535Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
