---
ID: "4f213a2b-bb2d-4c62-a846-984ba4ab774d"
Parent: "7d224925-e5ed-409a-83ef-0e97743cdac2"
Template: "7d224925-e5ed-409a-83ef-0e97743cdac2"
Path: /sitecore/templates/Project/Common/Page Types/Base Page/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180226T124008Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
